# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_auto_20170209_1500'),
        ('leave', '0005_auto_20170215_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApprover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approvers', to='payroll.EmployeeProfile')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ('name',)},
        ),
    ]
