# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_auto_20170215_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='no_of_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequestmessage',
            name='leave_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('C', 'Canceled')], default='P', max_length=2),
        ),
    ]
