# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_auto_20170215_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveRequestMessage',
            new_name='LeaveRequestApplication',
        ),
    ]
