# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_auto_20170216_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveApplication',
            new_name='LeaveApplicationReview',
        ),
    ]
