# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_auto_20170222_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='recurring',
            field=models.BooleanField(default=True, help_text='The day is is a holiday every year.'),
        ),
    ]
