# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-31 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_auto_20170222_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='positions',
        ),
    ]
