# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_holiday_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='recurring',
            field=models.BooleanField(default=True, help_text='The day is a holiday every year.'),
        ),
    ]
