# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0017_auto_20180803_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='CountryName',
        ),
    ]
