# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0019_auto_20180803_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='leave.CountryName'),
            preserve_default=False,
        ),
    ]
