# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-04 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0020_holiday_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryname',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='countryname',
            name='removed',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='countryname',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
