# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-09 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0052_auto_20170606_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('other_names', models.CharField(max_length=64)),
                ('source', models.CharField(choices=[('NP', 'Newspaper'), ('REF', 'Referral'), ('WEB', 'Website')], default='NP', max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('tel_number', models.CharField(max_length=16)),
                ('qualification', models.CharField(choices=[('NP', 'Newspaper'), ('REF', 'Referral'), ('WEB', 'Website')], default='QUALIFICATION_CHOICES', max_length=16)),
                ('experience_years', models.DecimalField(decimal_places=1, max_digits=3)),
                ('education_summary', models.TextField()),
                ('location', models.CharField(choices=[('KLA', 'Kampala'), ('JJA', 'Jinja'), ('MSK', 'Masaka'), ('MBR', 'Mbarara')], default='KLA', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=64)),
                ('due_date', models.DateField()),
                ('number_of_positions', models.IntegerField(default=1)),
                ('job_description', models.TextField()),
                ('reports_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeProfile')),
                ('service_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.ServiceLine')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.JobOpening'),
        ),
    ]
