# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-09 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='uploads/recrutment/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=32)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruitment.Candidate')),
            ],
        ),
    ]
