# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_candidatedocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobOpening',
            new_name='Vacancy',
        ),
    ]
