# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0052_auto_20170606_1812'),
        ('recruitment', '0003_auto_20170811_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='fields_of_education',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='minimum_education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EducationLevel'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='reports_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Position'),
        ),
    ]
