# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_auto_20170811_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='fields_of_education',
            field=models.TextField(blank=True, help_text='Separate with semi-colon (;)', null=True),
        ),
    ]
