# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_auto_20170811_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Position'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='service_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.ServiceLine'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
