# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_auto_20170811_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.CharField(choices=[('INT', 'Internal'), ('PUB', 'Public')], default='Internal', max_length=8),
        ),
    ]
