# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-12 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_auto_20170812_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 8, 12, 13, 55, 12, 844424, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
