# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_auto_20170814_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='source',
        ),
    ]
