# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_remove_jobapplication_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
