# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-16 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import recruitment.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_jobapplication_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicationshortlist',
            name='application',
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='other_names',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplicationdocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=recruitment.models.upload_directory),
        ),
        migrations.DeleteModel(
            name='JobApplicationShortList',
        ),
    ]
