# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-16 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0017_auto_20170816_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationshortlist',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='short_listed', to='recruitment.JobApplication'),
            preserve_default=False,
        ),
    ]
