# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-16 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0053_auto_20170811_1818'),
        ('recruitment', '0018_jobapplicationshortlist_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeProfile')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Vacancy')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobapplicationshortlist',
            name='application',
        ),
        migrations.DeleteModel(
            name='JobApplicationShortList',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='evaluation_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.EvaluationStage'),
        ),
    ]
