# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-16 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_auto_20170816_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationstage',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_stages', to='recruitment.Vacancy'),
        ),
    ]
