# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-16 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_auto_20170816_1244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluationstage',
            unique_together=set([('vacancy', 'name')]),
        ),
    ]
