# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0021_auto_20170816_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationstage',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=8),
        ),
    ]
