# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0022_evaluationstage_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='gender',
            new_name='required_gender',
        ),
        migrations.AlterField(
            model_name='evaluationstage',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=8),
        ),
    ]
