# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0025_auto_20170817_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='minimum_education',
            field=models.CharField(blank=True, choices=[('PRIMARY', 'Primary'), ('OLEVEL', "O'Level"), ('ALEVEL', "A'Level"), ('TERTIARY', 'Tertiary'), ('UNIVERSITY', 'University')], max_length=16, null=True),
        ),
    ]
