# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
    ]
