# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_remove_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_no',
            field=models.CharField(max_length=32),
        ),
    ]
