# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20171022_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
