# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20171027_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('returned_date', models.DateTimeField(null=True)),
                ('return_comment', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='assetallocation',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetallocation',
            name='employee',
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset.Category'),
        ),
        migrations.DeleteModel(
            name='AssetAllocation',
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='asset.Asset'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='asset_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='asset.AssetStatus'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
    ]
