# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20171027_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetAssignment',
            new_name='AssetIssuance',
        ),
    ]
