# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20171027_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetissuance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
