# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20171103_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='serial_no',
            new_name='id_number',
        ),
    ]
