# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_auto_20171202_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asset.IdType'),
            preserve_default=False,
        ),
    ]
