# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_auto_20171202_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='year_of_manufacture',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
