# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_asset_year_of_manufacture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='year_of_manufacture',
            new_name='date_of_manufacture',
        ),
    ]
