# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppraisalPeriod',
            new_name='Appraisal',
        ),
    ]
