# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0043_position_removed'),
        ('appraisal', '0002_auto_20170525_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_core', models.BooleanField(default=False)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Position')),
            ],
        ),
        migrations.AlterModelOptions(
            name='appraisal',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='appraisal',
            name='removed',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('0', 'Open'), ('1', 'Closed')], default='0', max_length=1),
        ),
    ]
