# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0046_remove_position_removed'),
        ('appraisal', '0003_auto_20170525_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=512)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='appraisalparameter',
            name='position',
        ),
        migrations.AddField(
            model_name='appraisalmeasure',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='appraisal.AppraisalParameter'),
        ),
        migrations.AddField(
            model_name='appraisalmeasure',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Position'),
        ),
    ]
