# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0046_remove_position_removed'),
        ('appraisal', '0004_auto_20170526_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='appraisal.AppraisalParameter')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='payroll.Position')),
            ],
        ),
        migrations.RemoveField(
            model_name='appraisalmeasure',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='appraisalmeasure',
            name='position',
        ),
        migrations.DeleteModel(
            name='AppraisalMeasure',
        ),
    ]
