# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0047_auto_20170531_1315'),
        ('appraisal', '0007_auto_20170526_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='employee_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeProfile'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='service_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.ServiceLine'),
        ),
        migrations.AlterField(
            model_name='appraisalmeasure',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
