# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0008_auto_20170531_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
