# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0048_auto_20170531_1601'),
        ('appraisal', '0009_auto_20170531_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('0', 'Complete'), ('1', 'Pending'), ('2', 'Canceled')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAppraisalFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.EmployeeAppraisal')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAppraisalMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('employee_appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='appraisal.EmployeeAppraisal')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.AppraisalMeasure')),
            ],
        ),
        migrations.AlterModelOptions(
            name='appraisal',
            options={'ordering': ('status', 'start_date')},
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Open'), ('1', 'Closed')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='employeeappraisal',
            name='appraisal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_appraisals', to='appraisal.Appraisal'),
        ),
        migrations.AddField(
            model_name='employeeappraisal',
            name='employee_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='payroll.EmployeeProfile'),
        ),
    ]
