# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0012_auto_20170602_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeappraisalmeasure',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
