# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0052_auto_20170606_1812'),
        ('appraisal', '0015_auto_20170606_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeappraisalmeasure',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeProfile'),
        ),
        migrations.AlterField(
            model_name='employeeappraisalmeasure',
            name='employee_appraisal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='appraisal.EmployeeAppraisal'),
        ),
        migrations.AlterField(
            model_name='employeeappraisalmeasure',
            name='measure',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='appraisal.AppraisalMeasure'),
        ),
    ]
