# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0016_auto_20170607_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeappraisalflow',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_flows', to='payroll.EmployeeProfile'),
        ),
    ]
