# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0052_auto_20170606_1812'),
        ('appraisal', '0017_auto_20170705_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorAppraisalMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('comment', models.TextField(blank=True)),
                ('employee_appraisal_measure', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_measure', to='appraisal.EmployeeAppraisalMeasure')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeProfile')),
            ],
        ),
    ]
