# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0052_auto_20170606_1812'),
        ('appraisal', '0018_supervisorappraisalmeasure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorappraisalmeasure',
            name='employee_appraisal_measure',
        ),
        migrations.RemoveField(
            model_name='supervisorappraisalmeasure',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='employeeappraisalflow',
            name='from_reviewer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_reviewers', to='payroll.EmployeeProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeappraisalflow',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_reviewers', to='payroll.EmployeeProfile'),
        ),
        migrations.DeleteModel(
            name='SupervisorAppraisalMeasure',
        ),
    ]
