# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0020_auto_20170712_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeappraisalflow',
            name='from_reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_reviewers', to='payroll.EmployeeProfile'),
        ),
        migrations.AlterField(
            model_name='employeeappraisalflow',
            name='to_reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_reviewers', to='payroll.EmployeeProfile'),
        ),
    ]
