# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0021_auto_20170712_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeappraisal',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='employeeappraisalflow',
            name='from_reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_submissions', to='payroll.EmployeeProfile'),
        ),
        migrations.AlterField(
            model_name='employeeappraisalflow',
            name='to_reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_receipts', to='payroll.EmployeeProfile'),
        ),
        migrations.AlterField(
            model_name='employeeappraisalmeasure',
            name='measure',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='appraisal.AppraisalMeasure'),
        ),
    ]
