# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 01:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0022_auto_20170713_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeappraisalmeasure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 13, 1, 58, 6, 105595, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
