# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0025_auto_20170720_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='comment',
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='description',
            field=models.CharField(help_text='(e.g. 1st quarter 2017)', max_length=32),
        ),
    ]
