# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0026_auto_20170720_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeappraisal',
            name='closed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeappraisal',
            name='on_close_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeappraisal',
            name='on_open_remarks',
            field=models.TextField(blank=True),
        ),
    ]
