# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0028_auto_20170721_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeappraisal',
            name='on_close_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeappraisal',
            name='on_open_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
