# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-10 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0084_auto_20180802_1702'),
        ('appraisal', '0029_auto_20170721_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalmeasure',
            name='service_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='measure_definitions', to='payroll.ServiceLine'),
            preserve_default=False,
        ),
    ]
