# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0084_auto_20180802_1702'),
        ('appraisal', '0030_appraisalmeasure_service_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('0', 'Failure'), ('1', 'Improvement Needed'), ('2', 'Excellent'), ('3', 'Exceptional')], default='1', max_length=1)),
                ('comment', models.TextField(null=True)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_classification', to='payroll.EmployeeProfile')),
            ],
        ),
    ]
