# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0031_performanceclassification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performanceclassification',
            name='employee_profile',
        ),
    ]
