# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0032_remove_performanceclassification_employee_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performanceclassification',
            old_name='status',
            new_name='classification',
        ),
    ]
