# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 02:35
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payroll.models.payroll_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=16)),
                ('taken_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_asset_allowance', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=64)),
                ('sort_code', models.CharField(max_length=32, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Bank')),
            ],
            options={
                'ordering': ['branch_name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=8, unique=True)),
                ('long_name', models.CharField(max_length=32, unique=True)),
                ('is_outreach', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('daily_outreach_allowance', models.CharField(blank=True, max_length=64, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Branch')),
            ],
            options={
                'ordering': ['long_name'],
            },
        ),
        migrations.CreateModel(
            name='ContractualPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('effective_since', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('symbol', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('affects_gross_pay', models.BooleanField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonorLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField()),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.AllowanceType')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[(b'0', b'Salaried'), (b'1', b'Consultant')], default=0, max_length=16)),
                ('employed_on', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[(b'0', b'Male'), (b'1', b'Female')], default=0, max_length=8)),
                ('nssf_number', models.CharField(max_length=16, unique=True)),
                ('bank_account_number', models.CharField(max_length=16, unique=True)),
                ('tin_number', models.CharField(max_length=16, unique=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('employee_number', models.CharField(blank=True, max_length=16, null=True)),
                ('other_names', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.CharField(choices=[(b'0', b'Active'), (b'1', b'Resigned'), (b'2', b'Terminated')], default=0, max_length=16)),
                ('allowances', models.ManyToManyField(to='payroll.AllowanceType')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.BankBranch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Category')),
                ('deductions', models.ManyToManyField(to='payroll.DeductionType')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by', to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeDesignation')),
            ],
            options={
                'ordering': ['user__last_name'],
                'permissions': (('can_view_system_info', 'Can view info: employees, branches, ...'), ('can_edit_employees', 'Can add/edit/remove employees'), ('can_view_payroll', 'Can view payroll'), ('can_edit_payroll', 'Can edit payroll'), ('can_authorize_payroll', 'Can authorize payroll'), ('can_send_payslips', 'Can send payslips'), ('can_monitor_activity', 'Can view activity report')),
            },
        ),
        migrations.CreateModel(
            name='EmployeeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunderProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Funder')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('session', models.CharField(blank=True, max_length=1024, null=True)),
                ('action', models.CharField(blank=True, max_length=1024, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_working_days', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('notified_recipients', models.BooleanField(default=False)),
                ('total_basic_pay', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('total_allowances', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('total_gross_pay', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('total_employee_nssf', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('total_msu_nssf', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('total_paye', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('total_deductions', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('total_net_pay', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('total_contractual_pay', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('authorized_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pay_period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payroll.PayPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nssf', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('paye', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('msu_nssf', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('advance', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('net_pay', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('total_allowances', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('total_deduction', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('gross_pay', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('taxable_income', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('total_days_worked', models.DecimalField(decimal_places=1, default=Decimal('-1'), max_digits=4)),
                ('contractual_pay_amount', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('basic_pay', payroll.models.payroll_models.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='PayslipAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.AllowanceType')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Payslip')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.DeductionType')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Payslip')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipFundsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Payslip')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.DonorLine')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('range_from', models.IntegerField(blank=True, null=True)),
                ('range_to', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='payslip',
            name='allowances',
            field=models.ManyToManyField(through='payroll.PayslipAllowance', to='payroll.AllowanceType'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='contractual_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.ContractualPay'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='deductions',
            field=models.ManyToManyField(through='payroll.PayslipDeduction', to='payroll.DeductionType'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Payroll'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeTitle'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donorline',
            name='funder_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.FunderProject'),
        ),
        migrations.AddField(
            model_name='contractualpay',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Currency'),
        ),
        migrations.AddField(
            model_name='contractualpay',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
