# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20170123_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeDesignation',
            new_name='JobTitle',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='designation',
            new_name='job_title',
        ),
    ]
