# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_position_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'ordering': ('level',)},
        ),
        migrations.AlterUniqueTogether(
            name='educationlevel',
            unique_together=set([('level', 'qualification')]),
        ),
    ]
