# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20170124_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='level',
            field=models.CharField(choices=[(b'PRIMARY', b'Primary'), (b'OLEVEL', b"O'Level"), (b'ALEVEL', b"A'Level"), (b'TERTIARY', b'Tertiary'), (b'UNIVERSITY', b'University')], max_length=16),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
