# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_auto_20170124_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationlevel',
            old_name='remarks',
            new_name='description',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='education_level_remarks',
            field=models.TextField(blank=True),
        ),
    ]
