# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20170124_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
