# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_auto_20170124_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
