# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_auto_20170124_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=256)),
                ('relationship', models.CharField(max_length=256)),
                ('phone_numbers', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='certifications',
            field=models.ManyToManyField(to='payroll.Certification'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 25, 7, 7, 8, 898455)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EducationLevel'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='marital_status',
            field=models.CharField(choices=[(b'S', b'Single'), (b'M', b'Married'), (b'D', b'Divorced')], default='S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='memberships',
            field=models.ManyToManyField(to='payroll.Membership'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.ManyToManyField(to='payroll.Skill'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_number',
            field=models.CharField(blank=True, default='1234', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_type',
            field=models.CharField(choices=[(b'S', b'Salaried'), (b'C', b'Consultant')], default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='other_names',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='256776666333', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='status',
            field=models.CharField(choices=[(b'A', b'Active'), (b'R', b'Resigned'), (b'T', b'Terminated')], default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Nationality'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='next_of_kin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.NextOfKin'),
        ),
    ]
