# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_auto_20170125_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationality',
            old_name='code',
            new_name='country_code',
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='marital_status',
            field=models.CharField(choices=[(b'S', b'Single'), (b'M', b'Married'), (b'D', b'Divorced')], default=(b'S', b'Single'), max_length=2),
        ),
    ]
