# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_auto_20170131_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextofkin',
            old_name='phone_numbers',
            new_name='contact',
        ),
    ]
