# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_auto_20170207_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='next_of_kin',
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeProfile'),
        ),
    ]
