# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_auto_20170207_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='employee_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeProfile'),
        ),
    ]
