# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_auto_20170207_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='certifications',
            field=models.ManyToManyField(blank=True, null=True, to='payroll.Certification'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EducationLevel'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='memberships',
            field=models.ManyToManyField(blank=True, null=True, to='payroll.Membership'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='payroll.Skill'),
        ),
    ]
