# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_auto_20170207_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='payroll.Certification'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='memberships',
            field=models.ManyToManyField(blank=True, to='payroll.Membership'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='payroll.Skill'),
        ),
    ]
