# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_auto_20170207_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextofkin',
            name='employee_profile',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='next_of_kin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payroll.NextOfKin'),
            preserve_default=False,
        ),
    ]
