# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_auto_20170208_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocumemt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=b'/tmp/')),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='documents',
        ),
        migrations.AddField(
            model_name='employeedocumemt',
            name='employee_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payroll.EmployeeProfile'),
        ),
    ]
