# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_auto_20170208_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocumemt',
            name='description',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
