# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_employeedocumemt_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeDocumemt',
            new_name='EmployeeDocument',
        ),
    ]
