# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import payroll.models.employee_models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_auto_20170208_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeProfile'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='description',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=payroll.models.employee_models.upload_directory),
        ),
    ]
