# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_auto_20170209_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'ordering': ['user__last_name'], 'permissions': (('can_setup_pim_info', 'Can configure Personnel Info'), ('can_setup_leave_info', 'Can configure Leave Info'), ('can_setup_payroll_info', 'Can configure Payroll Info'), ('can_view_system_info', 'Can view info: employees, branches, ...'), ('can_edit_employees', 'Can add/edit/remove employees'), ('can_view_payroll', 'Can view payroll'), ('can_edit_payroll', 'Can edit payroll'), ('can_authorize_payroll', 'Can authorize payroll'), ('can_send_payslips', 'Can send payslips'), ('can_monitor_activity', 'Can view activity report'))},
        ),
    ]
