# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0043_position_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
