# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0044_auto_20170525_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
