# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('payroll', '0049_auto_20170602_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='auth.Group'),
        ),
    ]
