# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0050_employeeprofile_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='roles',
        ),
    ]
