# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import payroll.models.employee_models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0053_auto_20170811_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=payroll.models.employee_models.profile_photo_upload_directory),
        ),
    ]
