# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0054_employeeprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advance',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employeeallowance',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Advance',
        ),
    ]
