# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 11:32
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import payroll.models.hrp_fields


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0055_auto_20171103_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRecurringAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', payroll.models.hrp_fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.AllowanceType')),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.DeductionType')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='donorline',
            name='funder_project',
        ),
        migrations.RemoveField(
            model_name='employeeallowance',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='employeeallowance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='funderproject',
            name='funder',
        ),
        migrations.RemoveField(
            model_name='payslipfundssource',
            name='payslip',
        ),
        migrations.RemoveField(
            model_name='payslipfundssource',
            name='source',
        ),
        migrations.DeleteModel(
            name='DonorLine',
        ),
        migrations.DeleteModel(
            name='EmployeeAllowance',
        ),
        migrations.DeleteModel(
            name='Funder',
        ),
        migrations.DeleteModel(
            name='FunderProject',
        ),
        migrations.DeleteModel(
            name='PayslipFundsSource',
        ),
    ]
