# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0056_auto_20171107_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerecurringadjustment',
            name='adjustment_type',
            field=models.CharField(default=2, max_length=4),
        ),
    ]
