# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-08 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0060_auto_20171108_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeerecurringadjustment',
            old_name='expires_at',
            new_name='expired_at',
        ),
    ]
