# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-08 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0061_auto_20171108_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='deductions',
        ),
        migrations.AlterField(
            model_name='employeerecurringadjustment',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 13, 12, 17, 836130, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payslipallowance',
            name='payslip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='payroll.Payslip'),
        ),
        migrations.AlterField(
            model_name='payslipdeduction',
            name='payslip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.Payslip'),
        ),
    ]
