# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0062_auto_20171108_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
