# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0063_auto_20171212_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancetype',
            name='is_taxed',
            field=models.BooleanField(default=True),
        ),
    ]
