# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-07 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0065_auto_20180907_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='driving_license',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='license_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='national_id_expiry',
            field=models.DateTimeField(blank=True, null=22),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='number_of_children',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='passport_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=22),
        ),
    ]
