# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0066_auto_20180725_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationship',
            field=models.CharField(choices=[('HUSBAND', 'Husband'), ('WIFE', 'Wife'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('MOTHER', 'Mother'), ('FATHER', 'Father'), ('SON', 'Son'), ('DAUGHTER', 'Daughter')], max_length=256),
        ),
    ]
