# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-07 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0067_auto_20180907_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('location', models.TextField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_type',
            field=models.CharField(choices=[('P', 'Permanent'), ('C', 'Temporary'), ('I', 'Internship')], default=('S', 'Single'), max_length=2),
        ),
    ]
