# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0068_auto_20180725_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
