# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0072_auto_20180725_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('location', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
