# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-31 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0075_auto_20180730_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='driving_license',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='number_of_hildren',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='serviceline',
            name='service_line_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.ServiceLineType'),
        ),
    ]
