# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-31 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0076_auto_20180731_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='number_of_hildren',
            new_name='number_of_children',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='license_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='national_id_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='passport_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=22),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=22),
        ),
    ]
