# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-31 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0078_auto_20180731_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='national_id_expiry',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_type',
            field=models.CharField(choices=[('P', 'Permanent'), ('C', 'Contract'), ('I', 'Internship')], default=('P', 'Permanent'), max_length=2),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
