# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-31 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0079_auto_20180731_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='national_id_expiry',
            field=models.DateTimeField(blank=True, null=22),
        ),
    ]
