# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import payroll.models.employee_models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0083_auto_20180801_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('full_name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('nin', models.CharField(blank=True, max_length=24, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=0, max_length=2)),
                ('relationship', models.CharField(choices=[('H', 'Spouse'), ('S', 'Son'), ('D', 'Daughter'), ('B', 'Brother'), ('T', 'Sister'), ('C', 'Cousin'), ('N', 'Niece'), ('P', 'Nephew'), ('O', 'Other')], default=False, max_length=64)),
                ('contact', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=payroll.models.employee_models.profile_photo_upload_directory)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='dependants',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.Dependants'),
        ),
    ]
