# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-20 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0085_auto_20180817_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='status_comment',
            field=models.TextField(blank=True),
        ),
    ]
