from django.conf.urls import url
from appraisal.views import *

urlpatterns = [

    url('^appraisal/$', AppraisalListView.as_view(), name='appraisal_list'),
    url('^appraisal/page(?P<page>\d+)/$', AppraisalListView.as_view(),
        name='appraisal_list_p'),    
    url('^lappraisal/new/$', AppraisalCreateView.as_view(), 
        name='appraisal_create'),
    url('^appraisal/edit/(?P<pk>\d+)/$', AppraisalUpdateView.as_view(), 
        name='appraisal_edit'),
    url('^appraisal/delete/(?P<pk>\d+)/$', AppraisalDeleteView.as_view(), 
        name='appraisal_delete'),

    url('^appraisalparam/$', AppraisalParameterListView.as_view(), 
        name='appraisal_parameter_list'),
    url('^appraisalparam/page(?P<page>\d+)/$', 
        AppraisalParameterListView.as_view(), 
        name='appraisal_parameter_list_p'),    
    url('^lappraisalparam/new/$', AppraisalParameterCreateView.as_view(), 
        name='appraisal_parameter_create'),
    url('^appraisalparam/edit/(?P<pk>\d+)/$',
        AppraisalParameterUpdateView.as_view(), 
        name='appraisal_parameter_edit'),
    url('^appraisalparam/delete/(?P<pk>\d+)/$', 
        AppraisalParameterDeleteView.as_view(), 
        name='appraisal_parameter_delete'),

    url('^appraisal/measure/$', AppraisalMeasureListView.as_view(), 
        name='appraisal_measure_list'),
    url('^appraisal/measure/page(?P<page>\d+)/$', 
        AppraisalMeasureListView.as_view(), 
        name='appraisal_measure_list_p'),    
    url('^lappraisal/measure/new/$', AppraisalMeasureCreateView.as_view(), 
        name='appraisal_measure_create'),
    url('^appraisal/measure/edit/(?P<pk>\d+)/$',
        AppraisalMeasureUpdateView.as_view(), 
        name='appraisal_measure_edit'),
    url('^appraisal/measure/delete/(?P<pk>\d+)/$', 
        AppraisalMeasureDeleteView.as_view(), 
        name='appraisal_measure_delete'),

    url('^empappraisal/$', EmployeeAppraisalListView.as_view(), 
        name='employee_appraisal_list'),
    url('^empappraisal/page(?P<page>\d+)/$', 
        EmployeeAppraisalListView.as_view(), 
        name='employee_appraisal_list_p'),
    url('^empappraisalms/(?P<emp_app_id>\d+)/$', 
        EmployeeAppraisalMeasureView.as_view(), 
        name='employee_appraisal_measure_list'),
    url('^empappraisalmspdf/(?P<emp_app_id>\d+)/$', 
        EmployeeAppraisalMeasurePdfView.as_view(), 
        name='employee_appraisal_measure_pdf'),
    url('^empappraisalms/(?P<emp_app_id>\d+)/page(?P<page>\d+)/$', 
        EmployeeAppraisalMeasureView.as_view(), 
        name='employee_appraisal_measure_list_p'),
    url('^lappraisal/empmeasure/update/(?P<pk>\d+)/$', 
        EmployeeAppraisalMeasureUpdateView.as_view(), 
        name='employee_appraisal_measure_update'),
        
    url('^empappraisal/submit/(?P<pk>\d+)/$', AppraisalFlowCreateView.as_view(), 
        name='employee_appraisal_submit'),

    url('^recempappraisal/$', ReceivedEmployeeAppraisalListView.as_view(), 
        name='received_employee_appraisal_list'),
    url('^recempappraisal/page(?P<page>\d+)/$', 
        ReceivedEmployeeAppraisalListView.as_view(), 
        name='received_employee_appraisal_list_p'),
    url('^recempappraisams/(?P<emp_app_id>\d+)/$', 
        ReceivedEmployeeAppraisalMeasureView.as_view(), 
        name='received_employee_appraisal_measure_list'),
    url('^recempappraisams/(?P<emp_app_id>\d+)/page(?P<page>\d+)/$', 
        ReceivedEmployeeAppraisalMeasureView.as_view(), 
        name='received_employee_appraisal_measure_list_p'),
    url('^lappraisal/recempmeasure/update/(?P<pk>\d+)/$', 
        ReceivedAppraisalMeasureUpdateView.as_view(), 
        name='received_appraisal_measure_update'),
        
    url('^reports/performance/$', PreformanceSummaryReport.as_view(), 
        name='performance_summary'),
    url('^reports/performance/(?P<appraisal_id>\d+)/pdf/$', 
        PerformanceSummaryPdfReportView.as_view(), name='performance_summary_pdf'),
    url('^reports/performance/(?P<appraisal_id>\d+)/csv/$', 
        PerformanceSummaryPdfReportView.as_view(), name='performance_summary_csv'),

#    url('^recempappraisal/submit/(?P<pk>\d+)/$', 
#        SupervisorAppraisalMeasureUpdateView.as_view(), 
#        name='supervisor_appraisal_measure_list'),

]