#!/bin/bash

NAME="hrp_pregtech"                                  # Name of the application
DJANGODIR=/home/pregtech/hrp_pregtech # Django project directory
SOCKFILE=/tmp/gunicorn_hrp_pregtech.sock  # we will communicte using this unix socket
USER=pregtech
GROUP=pregtech
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=hrp.settings.prod             # which settings file should Django use
DJANGO_WSGI_MODULE=hrp.wsgi                     # WSGI module name
PORT=7001
LOCAL_IP="0.0.0.0"

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
#source ../bin/activate
source /home/pregtech/.envs/hrp/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
#exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
exec /home/pregtech/.envs/hrp/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --pythonpath=/home/pregtech/.envs/hrp/bin/ \
  --log-level=debug \
  --bind=unix://$SOCKFILE \
  --log-file=-
  #--bind=$LOCAL_IP:$PORT \

  #--bind=unix:$SOCKFILE \
